### ISSUE TITLE
Generating Keyframes in MAYA 2020

### ISSUE THREAD

**Issue by martin-madrid** [joaen/maya-auto-lip-sync#1]
Hi,

I seem to be having issues using this .wav file (resampled to 16kHz mono) and accompanying text file in generating keyframes for my animation.

wav and txt files: https://drive.google.com/drive/folders/1ghHfuH8O9Xg-8JUCLX91fQIZulmw9doo?usp=sharing

![image](https://github.com/joaen/maya-auto-lip-sync/assets/67848587/4c352dac-dc01-49e2-af3f-99d6e5bf9832)

Any solution would be greatly appreciated, thanks :)

**Comment by joaen** [comment]
Hi! Could you please try naming the .txt-file so it has the same name as .wav-file?

I'm sorry for the lack of error handling. That's something I want to address in the future.

**Comment by martin-madrid** [comment]
Hi, thanks for the reply.

I've tried renaming both files to speech.wav and speech.txt and still seem to have the same issue.

![image](https://github.com/joaen/maya-auto-lip-sync/assets/67848587/8c7fde96-1acf-48b3-aed6-84990b83045c)

**Comment by joaen** [comment]
Ah, ok. I think I found the issue. I will submit a fix later tonight!

**Comment by joaen** [comment]
I updated the script. Please try syncing the latest from github and make sure that the montreal-forced-aligner is in the correct folder. Let me know how it goes!

**Comment by martin-madrid** [comment]
Hi,

Thanks for the update. I believe there is a problem with running mfa_align.exe.

![image](https://github.com/joaen/maya-auto-lip-sync/assets/67848587/52d4d966-28dc-4056-84b9-e00f4acba179)

**Comment by joaen** [comment]
It seems like your montreal-force-aligner folder path is incorrect.

Does this path exist? `C:/Users/[user]/Documents/maya/2020/scripts/montreal-forced-aligner/bin/mfa_align.exe`

**Comment by martin-madrid** [comment]
It seems like when the project file is not located in the C: drive, it fails to run the mfa_align subprocess (despite your auto-lip-sync.py correctly identifying the appropriate paths). When moving the project file into the C: drive, it now recognises mfa_align.

![image](https://github.com/joaen/maya-auto-lip-sync/assets/67848587/afc63eb8-2c78-4bdc-9c98-4e624d1e2e90)

Overall, I am happy to confirm that your script is now working correctly on MAYA 2020! Thanks for all the support! :)
