### ISSUE TITLE
can't start the tool

### ISSUE THREAD

**Issue by rafadiasm** [joaen/maya-auto-lip-sync#13]
Hey, thanks for sharing this tool, the code is very organized and i rly wanna try it but i can't seem to get it to work :v
i went through the step by step and used the auto-installer for the dependencies, but when i run the starter script in maya (2019) i only get the error:
# Error: SyntaxError: file C:/Users/me/Documents/maya/2019/scripts\auto_lip_sync\__init__.py line 2: invalid syntax # 
I tried it on two computers and get the same error, am i doing something wrong?

**Comment by joaen** [comment]
Hi, which windows version are you using?

**Comment by joaen** [comment]
Also please tell me which Python version you are running in Maya. You can run this in the Maya script editor:
```
import sys
print(sys.version)
```

**Comment by joaen** [comment]
This seem to be an oversight by me. print (end="") doesn't exist in Python2

Comment out line: 311 and 316 to fix it.
