### ISSUE TITLE
Probelm in Generating Key Frame

### ISSUE THREAD

**Issue by satori1216** [joaen/maya-auto-lip-sync#3]
Hello joaen, thank you for creating and sharing this script! 

I downloaded this script today and currently having some problems when generating the keyframes. The .wav file is resampled to 16kHz mono and has the same name as the .txt file. After I pressed the "Generate Keyframes" button, it showed "Done! Everything took..." in the script editor and then suddenly jumped to the situation that shows in the screenshot below
![lipsnc_issue](https://github.com/joaen/maya-auto-lip-sync/assets/138416596/f2b856f6-8062-4e41-adba-4c4bd9216fbe)

The "Cancel" button did not work, nor were the keyframes generated on the timeline. The progress bar didn't move no matter how long you wait. I also tried several times with different rigs and the results are the same. (I'm using Maya 2022).

Greatly appreciated any solution. Thank you! :)

**Comment by joaen** [comment]
Hi! Let me see if I can repro this bug. If possible it would be helpful if you could share a link to the wav-file and the txt-file which you are using.

**Comment by satori1216** [comment]
I directly downloaded the audio and text files from the google drive link provided in the closed issue of this code: https://drive.google.com/drive/folders/1ghHfuH8O9Xg-8JUCLX91fQIZulmw9doo?usp=sharing
and changed them to the same name, which is the t0001.wav and t0001.txt you can see in the screenshot.

**Comment by rombick** [comment]
> I directly downloaded the audio and text files from the google drive link provided in the closed issue of this code: https://drive.google.com/drive/folders/1ghHfuH8O9Xg-8JUCLX91fQIZulmw9doo?usp=sharing and changed them to the same name, which is the t0001.wav and t0001.txt you can see in the screenshot.

comment out lines 305-311 in auto_lip_sync.py and it should work

**Comment by joaen** [comment]
I just updated the script with two bug fixes:

- Added a fail safe in the load_pose function so items() is used if the user is running Python 3. iteritems() broke the script when running it with Python 3. 

- Added a fail safe that empty lines from the MFA cli should be ignored. For some reason empty lines were printed which created an infinite loop. (Thanks @rombick for pointing me to where the issue were in the script).
