### ISSUE TITLE
error

### ISSUE THREAD

**Issue by harman110** [joaen/maya-auto-lip-sync#4]
make sure your input data and poses are correctly set up...... 
i have tried 2 different audios on 2 different rigs still the same error please help me out

**Comment by JonesyPMD** [comment]
Hey, did you find a solution for this?

**Comment by joaen** [comment]
Could you please post the whole error message here?
There should be more info above the error message you posted, in the Maya script editor log.

**Comment by enigma-dy** [comment]
pls can you do a tutorial on how to install. finding it difficult to install

**Comment by joaen** [comment]
I need an error log to be able to to help. Without any information it's hard to tell what exactly went wrong when running the tool.

**Comment by joaen** [comment]
> pls can you do a tutorial on how to install. finding it difficult to install

1. Download and add the auto_lip_sync.py to your Maya scripts folder. 
2. Add the DEPENDENCIES_INSTALLER.bat to your Maya scripts folder and run the bat-file from there.
3. In Maya you should be able to run these lines in script editor to start the script:

```
import auto_lip_sync
auto_lip_sync.start()
```
